registry: txt
txtOwnerId: "k8s-external-dns-weebcluster-1"
txtPrefix: "k8s-external-dns-"

domainFilters:
- daleajackson.io

provider: rfc2136

extraArgs:
- --rfc2136-host=172.16.20.201
- --rfc2136-port=53
- --rfc2136-zone=daleajackson.io
- --rfc2136-insecure
- --rfc2136-tsig-axfr